---
- name: "Set environment variables"
  hosts: centos

  tasks:
    - name: Add an environment variable tp the remote user's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: "^ENV_VAR="
        line: "ENV_VAR=Hello_world!"

    - name: Get the value of an environment variable
      shell: "source ~/.bash_profile && echo $ENV_VAR"
      register: foo # registers CLI output to a variable "foo"

    - debug: msg="The variable is {{ foo.stdout }}"
