# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "srv1" do |app|
    app.vm.hostname = "srv1.test"
    app.vm.network :private_network, ip: "192.168.56.101"
  end

  # Application server 2
  config.vm.define "srv2" do |app|
    app.vm.hostname = "srv2.test"
    app.vm.network :private_network, ip: "192.168.56.102"
  end

  # Database server
  config.vm.define "srv3" do |app|
    app.vm.hostname = "srv3.test"
    app.vm.network :private_network, ip: "192.168.56.103"
  end
end
