---
- name: Ensure Apache is installed.
  package:
    name: "{{ apache_package }}"
    state: present

- name: Ensure Apache is running and starts at boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
