# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "project-app1.test"
    app.vm.network :private_network, ip: "192.168.49.101"
  end

  # Application server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "project-app2.test"
    app.vm.network :private_network, ip: "192.168.49.102"
  end

  # Database server
  config.vm.define "db1" do |app|
    app.vm.hostname = "project-db1.test"
    app.vm.network :private_network, ip: "192.168.49.201"
  end
end
